Numpy의 특징이 존재함

In [2]:
import numpy as np

In [3]:
int_array = np.array([-2, -1, 0, 1, 2])

In [4]:
int_array

array([-2, -1,  0,  1,  2])

행렬 만들어 보기 - 행렬은 그 크기가 항상 같아야 합니다.

In [6]:
matrix = np.array([[-1, 0, 1], [-3, 4, 3]])

In [7]:
matrix

array([[-1,  0,  1],
       [-3,  4,  3]])

In [10]:
array3d = np.array([[[-1, 0, 1], [-3, 4, 3]], [[-1, 0, 1], [-3, 4, 3]]])

In [11]:
array3d

array([[[-1,  0,  1],
        [-3,  4,  3]],

       [[-1,  0,  1],
        [-3,  4,  3]]])

In [12]:
ints = np.array([-2, -1, 0, 1, 2], dtype=np.short)

In [13]:
ints

array([-2, -1,  0,  1,  2], dtype=int16)

In [14]:
ints = np.array([-2, -1, 0, 1, 2], dtype=np.ushort)

In [15]:
ints

array([65534, 65535,     0,     1,     2], dtype=uint16)

numpy.arrage에 대해서 알아보자


In [17]:
first_three = np.arange(3)
first_three

array([0, 1, 2])

In [19]:
starts_at_minus_2 = np.arange(-2,3)
starts_at_minus_2

array([-2, -1,  0,  1,  2])

In [21]:
first_event = np.arange(0, 11, 2)
first_event

array([ 0,  2,  4,  6,  8, 10])